### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ahmtaras** [pienter-tech/gridsome-source-directus#2]
**Dependencies**
"@pienter/gridsome-source-directus": "^1.0.0",
"gridsome": "^0.7.12"

**ERROR**
Directus 1. Login in
Directus 2. Getting collections
`(node:1056) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined
    at Object.exports.parse (C:\Users\ahmta\Desktop\my-gridsome-site\node_modules\stack-trace\lib\stack-trace.js:21:12)
    at getCallSite (C:\Users\ahmta\Desktop\my-gridsome-site\node_modules\gridsome\index.js:75:21)
    at C:\Users\ahmta\Desktop\my-gridsome-site\node_modules\gridsome\index.js:45:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a 
promise which was not handled with .catch(). (rejection id: 2)
(node:1056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by doughnet** [comment]
Was this ever resolved?

**Comment by ahmtaras** [comment]
@doughnet 
I don't know if the problem has been fixed. [I am using this repo.](https://github.com/peXed/gridsome-source-directus)

**Comment by doughnet** [comment]
Thanks.  I didn't have much luck with that repo either.

I get the same issue you did using this repo unfortuantely.

Directus 3. Getting relations
Directus 4. Getting files
Directus 5. Setting up GraphQL Schema
TypeError: Cannot read property 'addReference' of undefined
    at relations.forEach.relation (/home/USERNAME/classes/gridsome/directus/node_modules/@pienter/gridsome-source-directus/index.js:239:46)
    at Array.forEach (<anonymous>)
    at DirectusSource.fetchContent (/home/USERNAME/classes/gridsome/directus/node_modules/@pienter/gridsome-source-directus/index.js:238:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by OzzyTheGiant** [comment]
I don't think this is getting resolved anytime soon. Directus 9 is on the verge of releasing and that broke @peXed gridsome-source-directus plugin.
